# permissions for end users to edit applicationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd-addon
    app.kubernetes.io/managed-by: kustomize
  name: applicationtemplate-editor-role
rules:
- apiGroups:
  - argocd-addon.github.com
  resources:
  - applicationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd-addon.github.com
  resources:
  - applicationtemplates/status
  verbs:
  - get
