//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTemplate) DeepCopyInto(out *ApplicationTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTemplate.
func (in *ApplicationTemplate) DeepCopy() *ApplicationTemplate {
	if in == nil {
		return nil
	}
	out := new(ApplicationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTemplateList) DeepCopyInto(out *ApplicationTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTemplateList.
func (in *ApplicationTemplateList) DeepCopy() *ApplicationTemplateList {
	if in == nil {
		return nil
	}
	out := new(ApplicationTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTemplateSpec) DeepCopyInto(out *ApplicationTemplateSpec) {
	*out = *in
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Kustomize != nil {
		in, out := &in.Kustomize, &out.Kustomize
		*out = new(KustomizeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTemplateSpec.
func (in *ApplicationTemplateSpec) DeepCopy() *ApplicationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTemplateStatus) DeepCopyInto(out *ApplicationTemplateStatus) {
	*out = *in
	if in.MatchedClusters != nil {
		in, out := &in.MatchedClusters, &out.MatchedClusters
		*out = make([]MatchedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RenderedFiles != nil {
		in, out := &in.RenderedFiles, &out.RenderedFiles
		*out = make([]RenderedFile, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTemplateStatus.
func (in *ApplicationTemplateStatus) DeepCopy() *ApplicationTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSelector) DeepCopyInto(out *ClusterSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSelector.
func (in *ClusterSelector) DeepCopy() *ClusterSelector {
	if in == nil {
		return nil
	}
	out := new(ClusterSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmConfig) DeepCopyInto(out *HelmConfig) {
	*out = *in
	if in.RenderTargets != nil {
		in, out := &in.RenderTargets, &out.RenderTargets
		*out = make([]HelmRenderTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmConfig.
func (in *HelmConfig) DeepCopy() *HelmConfig {
	if in == nil {
		return nil
	}
	out := new(HelmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmRenderTarget) DeepCopyInto(out *HelmRenderTarget) {
	*out = *in
	in.DestinationCluster.DeepCopyInto(&out.DestinationCluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmRenderTarget.
func (in *HelmRenderTarget) DeepCopy() *HelmRenderTarget {
	if in == nil {
		return nil
	}
	out := new(HelmRenderTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizeConfig) DeepCopyInto(out *KustomizeConfig) {
	*out = *in
	if in.RenderTargets != nil {
		in, out := &in.RenderTargets, &out.RenderTargets
		*out = make([]KustomizeRenderTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizeConfig.
func (in *KustomizeConfig) DeepCopy() *KustomizeConfig {
	if in == nil {
		return nil
	}
	out := new(KustomizeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizeRenderTarget) DeepCopyInto(out *KustomizeRenderTarget) {
	*out = *in
	in.DestinationCluster.DeepCopyInto(&out.DestinationCluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizeRenderTarget.
func (in *KustomizeRenderTarget) DeepCopy() *KustomizeRenderTarget {
	if in == nil {
		return nil
	}
	out := new(KustomizeRenderTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchedCluster) DeepCopyInto(out *MatchedCluster) {
	*out = *in
	if in.MatchedLabels != nil {
		in, out := &in.MatchedLabels, &out.MatchedLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchedCluster.
func (in *MatchedCluster) DeepCopy() *MatchedCluster {
	if in == nil {
		return nil
	}
	out := new(MatchedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderedFile) DeepCopyInto(out *RenderedFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderedFile.
func (in *RenderedFile) DeepCopy() *RenderedFile {
	if in == nil {
		return nil
	}
	out := new(RenderedFile)
	in.DeepCopyInto(out)
	return out
}
